### PR TITLE
feat: add snap

### PR DESCRIPTION
**Pull request by BearToCode**
Now you can add snapSize="..." to allow the user to close panes by simply getting the pane close enough to the maximum and minimum size.

### CODE REVIEW

**Comment by orefalo** [comment]
Hi @BearToCode and thank you so much for your contribution.

If I may, can you provide more insights? 
  Did you grab the idea from another project/tool?
  How you are planning to use it? (Not from the tech side)
... I am asking b/c I am not used to see splitters with a snap feature and I don't see the benefit from a CX standpoint.

Please enlighten me.

**Comment by BearToCode** [comment]
Hello,

I am currently creating a desktop application that has multiple windows that the user can open, close and resize, very similarly to what you do on vscode and other IDEs, which have some sort of snap to let the user minimize the windows without actually closing them. I previously used [SplitJS](https://github.com/nathancahill/split/tree/master/packages/splitjs#snapoffset-default-30) to achieve a similar result, which also has a [React component](https://github.com/nathancahill/split/tree/master/packages/react-split#react-split----).

Here is a example from vscode:

main-window svelte-numerus-app-Visual-Studio-Code-2022-06-27-22-23-33

**Comment by BearToCode** [comment]
> > Hello,
> > I am currently creating a desktop application that has multiple windows that the user can open, close and resize, very similarly to what you do on vscode and other IDEs, which have some sort of snap to let the user minimize the windows without actually closing them. I previously used [SplitJS](https://github.com/nathancahill/split/tree/master/packages/splitjs#snapoffset-default-30) to achieve a similar result, which also has a [React component](https://github.com/nathancahill/split/tree/master/packages/react-split#react-split----).
> > Here is a example from vscode:
> > main-window svelte-numerus-app-Visual-Studio-Code-2022-06-27-22-23-33
> >       
> >         [
> >           
> >         ](https://user-images.githubusercontent.com/47280851/176030392-09105a19-8caa-4c68-bb47-072a793955e2.gif)
> >         
> >             main-window svelte-numerus-app-Visual-Studio-Code-2022-06-27-22-23-33
> >           
> >         
> >           
> >             
> >               
> >             
> >             
> >               
> >               
> >             
> >           
> >           [
> >             
> >               
> >             
> >           ](https://user-images.githubusercontent.com/47280851/176030392-09105a19-8caa-4c68-bb47-072a793955e2.gif)
> >         
> >        [ ](https://user-images.githubusercontent.com/47280851/176030392-09105a19-8caa-4c68-bb47-072a793955e2.gif) main-window svelte-numerus-app-Visual-Studio-Code-2022-06-27-22-23-33
> >       
> >         [
> >           
> >         ](https://user-images.githubusercontent.com/47280851/176030392-09105a19-8caa-4c68-bb47-072a793955e2.gif)
> >         
> >             main-window svelte-numerus-app-Visual-Studio-Code-2022-06-27-22-23-33
> >           
> >         
> >           
> >             
> >               
> >             
> >             
> >               
> >               
> >             
> >           
> >           [
> >             
> >               
> >             
> >           ](https://user-images.githubusercontent.com/47280851/176030392-09105a19-8caa-4c68-bb47-072a793955e2.gif)
> >         
> >        [ ](https://user-images.githubusercontent.com/47280851/176030392-09105a19-8caa-4c68-bb47-072a793955e2.gif)
> 
> It is a nice feature. Do you think this feature should be as part of the library, or by the user itself by listening to the resize event?

Well, I created a pull request because I wanted to share how I achieved it. I don't think it's that easy to recreate the same effect using the events provided, although I could be wrong.
I just think it could be a nice touch for the library!

**Comment by orefalo** [comment]
Very nice, makes sense 
Thank you for all these details - neat application!
- will merge today
Sincerely

**Comment by Tal500** [comment]
I do think that this is a nice feature, I just want to discuss it a little bit.

1. I think we should have some `snapped` event(s) 
2. I did understand how it can be snapped at the minimum and disappear, I just didn't understand how can it be snapped at the maximum. What does it mean? How can it be more than the maximum?
3. In addition to 2, what will happen in the case you have 2 panes, with a maximum cap on the first. Could the second one be possibly snapped?
4. How do you suggest to implement/use the ability to disable snapping? Simply just by putting a big number in "snapSize"?
5. About CSS size transition - Do you suggest to have a smooth transition effect during snapping? Or just let it be configurable? If so, what will be the default?

**Comment by BearToCode** [comment]
> Very nice, makes sense Thank you for all these details - neat application!
> 
> Update: @BearToCode - If I may, what is missing in the library to implement the same functionality "outside" the core?
> 
> This is how it could work. Your extensions would trap the "resize" event, apply math to detect the snap boundary, force the size programmatically when it applies.
> 
> Trying to see if we can make the feature less intrusive, keep a slim core, while still providing great features as "extensions".
> 
> Let us know,

You would need to implement a custom function that can override the default one, read the panes properties and return the new size. This is what my implementation currently does, and it can be easily ported in a separate function. However, I think having the snapSize property allows for easier access to the panes properties, and removing it would force user to read some properties of their own.


> I do think that this is a nice feature, I just want to discuss it a little bit.
> 
> 1. I think we should have some `snapped` event(s)
> 2. I did understand how it can be snapped at the minimum and disappear, I just didn't understand how can it be snapped at the maximum. What does it mean? How can it be more than the maximum?
> 3. In addition to 2, what will happen in the case you have 2 panes, with a maximum cap on the first. Could the second one be possibly snapped?
> 4. How do you suggest to implement/use the ability to disable snapping? Simply just by putting a big number in "snapSize"?
> 5. About CSS size transition - Do you suggest to have a smooth transition effect during snapping? Or just let it be configurable? If so, what will be the default?

Snapping to the maximum actually mean setting to the minimum the next panel, so that the current one can occupy all his size. It does not goes over the maximum. To answer to you third point, I made it so the panes can snap to theirs maximum size or their neighbours minimum one. I also want to point out that the feature is absolutely optional; the default value is set to zero, and with that it works just like normal. There should be no problem with the snapped events, while for the CSS transition I think a normal one should work fine.

Also, I updated the commit with some improvements:
1. Now setting the snap size on one panels allows it to also snap to maximum, even when the adjacent panels don't have the snap enable.
2. I fixed a bug I introduced for no reason on the previous commit that made the snapSize undefined if not set.
3. I fixed what I think is a bug on line 425, replacing 
```ts
paneAfter.max() < 100 && dragPercentage <= 100 - (paneAfter.max() + sumNextPanesSize(splitterIndex + 1));
```
```ts
paneAfter.max() < 100 && dragPercentage <= 100 - (paneAfter.max() + sums.nextPanesSize);
```
This caused some clunky behaviour and caused ```paneAfterMaxReached``` to be set to ```true``` in wrong occasions.


Here are some examples of what the snapSize currently does:

2gif
4gif
5gif
3gif
1gif

**Comment by Tal500** [comment]
Looks good overall!
Few things though:
1. We still need to fire an event of `snapped` with some details. Doesn't block this PR, but something that we should remember.
2. I believe there should be two parameters instead of one: `maxSizeMax` and `minSnapSize`, for each case. You should also state in the Readme that 0 means no snap.
3. What about the following conflicting case:
 * two panes
 * minSnapSizes for the **second** 1%
 * the first has maximum size of 90%
 * the second has a minimum size of 50%
   If the user start dragging toward the second pane, would the second pane be snapped? It must not be snapped, since it violates the maximum size of the first pane! Will it be snapped only to a size of 10%(do you consider this as the good behaviour)?
4. We made many changes to the project. Can you merge the branch "master" to your one? Notice that now we use pnpm and you need to commit via `npm run commit`

**Comment by Tal500** [comment]
Another question happens to be on my mind:
What does make more sense in your mind, to hide via `display: none;` the snapped pane, or to set its size to `0`?

For me is the former.
This is a little bit related to my previous conflicting case dilema, where there you must set some size and display the pane, even when it's snapped.

**Comment by orefalo** [comment]
I believe it is, except for the branch which shows as "conflicting".

@BearToCode thank you! can I ask you to rebase (or merge) against master?

**Comment by Tal500** [comment]
> I believe it is, except for the branch which shows as "conflicting".
> 
> @BearToCode thank you! can I ask you to rebase (or merge) against master?

I am not a huge fan of rebasing, rather prefer to use merging.

I can handle this I think.

**Comment by BearToCode** [comment]
> > I believe it is, except for the branch which shows as "conflicting".
> > @BearToCode thank you! can I ask you to rebase (or merge) against master?
> 
> I am not a huge fan of rebasing, rather prefer to use merging.
> 
> I can handle this I think.

Too late, I hope I haven't messed think up...

**Comment by Tal500** [comment]
> > > I believe it is, except for the branch which shows as "conflicting".
> > > @BearToCode thank you! can I ask you to rebase (or merge) against master?
> > 
> > 
> > I am not a huge fan of rebasing, rather prefer to use merging.
> > I can handle this I think.
> 
> Too late, I hope I haven't messed things up...

No you didn't, not too terrible. You had make our job much easier though.
The code style check will be solve by a manual merge(together with automatic prettifying) I shall perform.

**Comment by Tal500** [comment]
Sorry to bother again but I need to fight again after testing by myself.

I see that panes are also snapped when reaching to their maximum possible size (see the "Middle snap" example for compression). Why is that? I thought you snap only to the minimum size always.
As I believed we have just argued, that if the user would like to get a snap effect for the maximal possible size, he should declare the neighbor pane as a snapped, since it should go only for the minimum.
Don't you agree with this logic?

In the example I said, if you would like to snap also to maximum, I believe you should replace
https://github.com/orefalo/svelte-splitpanes/blob/9f5ecc600753fc7b9e9889c654601230e34ca8c4/src/comp/MiddleSnap.svelte#L25-L39
with
```svelte
<Splitpanes style="height: 400px">
  <Pane snapSize="10">
    
  </Pane>

  <Pane snapSize="10">
    <span style="font-size: 20px;">
      I have a snap size of 10%
    </span>
  </Pane>

  <Pane snapSize="10">
    
  </Pane>
</Splitpanes>
```

Anyway, I have a [snap branch](https://github.com/orefalo/svelte-splitpanes/tree/snap) ready for now. If you make any change, please merge from this one.

**Comment by BearToCode** [comment]
I'll fix it as soon as I can, it won't take much, but how can I update the other branch? Do I need to create another PR?

**Comment by Tal500** [comment]
Accidentally I have edit your comment instead of replying....
Anyway read your comment again😂

**Comment by orefalo** [comment]
Gentlemen, glad to see a community building up.
Let me know if you need any help.
Sincerely,

**Comment by BearToCode** [comment]
Anyway, that's the fix, so that you can implement it yourself:

at line ~400 use this:
```ts
// Calculate drag percentage
		const mouseDragPercentage = Math.max(Math.min(getCurrentDragPercentage(drag), maxDrag), minDrag);

		// Handle snap
		const paneBeforeSnap = Math.max(
			// Snap due to the previous pane reaching minimum size
			sums.prevPanesSize + paneBefore.min() + paneBefore.snap(),
			// and to the next one reaching maximum size
			100 - (sums.nextPanesSize + paneAfter.max()) + paneAfter.snap()
		);

		const paneAfterSnap = Math.min(
			// Snap due to the next pane reaching minimum size
			100 - (sums.nextPanesSize + paneAfter.min() + paneAfter.snap()),
			// and to the previous one reaching maximum size
			sums.prevPanesSize + paneBefore.max() - paneBefore.snap()
		);
```

**Comment by Tal500** [comment]
> Anyway, that's the fix, so that you can implement it yourself:
> 
> at line ~400 use this:
> 
> ```ts
> // Calculate drag percentage
> const mouseDragPercentage = Math.max(Math.min(getCurrentDragPercentage(drag), maxDrag), minDrag);
> 
> // Handle snap
> const paneBeforeSnap = Math.max(
> 	// Snap due to the previous pane reaching minimum size
> 	sums.prevPanesSize + paneBefore.min() + paneBefore.snap(),
> 	// and to the next one reaching maximum size
> 	100 - (sums.nextPanesSize + paneAfter.max()) + paneAfter.snap()
> );
> 
> const paneAfterSnap = Math.min(
> 	// Snap due to the next pane reaching minimum size
> 	100 - (sums.nextPanesSize + paneAfter.min() + paneAfter.snap()),
> 	// and to the previous one reaching maximum size
> 	sums.prevPanesSize + paneBefore.max() - paneBefore.snap()
> );
> ```
> 
> I had also updated an example, but I just added two adjacent panes with snap to let the user see how they interact.
> 
> Since this is my last comment (I hope) I'd like to thank you for your work, you did a great job with this library!


```

OK, will handle this.

Don't forget to do "pnpm install" and "pnpm format" in general.

**Comment by orefalo** [comment]
@BearToCode  it's all in the README.

in a nutshell, just run npm run commit (from the command line) and follow the prompts

**Comment by BearToCode** [comment]
> @BearToCode it's all in the README.
> 
> in a nutshell, just run npm run commit (from the command line) and follow the prompts

That's what I did, but I get the error mentioned above after I file up all the info.
Maybe is my fault, so, when the new version is released, I'll try to merge and see if the problem persists.

**Comment by orefalo** [comment]
ok, I am curious to get your feedback as we are trying to ease the experience.

**Comment by Tal500** [comment]
> > @BearToCode it's all in the README.
> > in a nutshell, just run npm run commit (from the command line) and follow the prompts
> 
> That's what I did, but I get the error mentioned above after I file up all the info. Maybe is my fault, so, when the new version is released, I'll try to merge and see if the problem persists.

Did you re-run `pnpm install`?

**Comment by BearToCode** [comment]
> > > @BearToCode it's all in the README.
> > > in a nutshell, just run npm run commit (from the command line) and follow the prompts
> > 
> > 
> > That's what I did, but I get the error mentioned above after I file up all the info. Maybe is my fault, so, when the new version is released, I'll try to merge and see if the problem persists.
> 
> Did you re-run `pnpm install`?

Yes

**Comment by Tal500** [comment]
Please accept https://github.com/BearToCode/svelte-splitpanes/pull/2 so we can continue.

I also changed the code to allow only snap to the minimum direction.
There were a problem with the pane pushing, so I made a hack to disable it on snapping for now (should be fixed for good in the future).
See [my changes in the code here](https://github.com/orefalo/svelte-splitpanes/commit/a74b092ad19b056e6069e6c64766ca623c387f3a#diff-09fecdf9d3beab3e46c2b4d951444190976b1a5acc07616d15b7f00836ead343).

Do you accept?
If yes, please reply here "yes" and also accept the PR I have pushed to your repo.

**Pull request merged**
