### PR TITLE
Qa tools

### PR DESCRIPTION
**Pull request by orefalo**
For your review, Tal.

I recommend you start from the README

in a nutshell, you can commit with `npm run commit`

### CODE REVIEW

**Comment by orefalo** [comment]
Looking at the diff, looks like formatting for applied as well ;-)

**Comment by Tal500** [comment]
See the errors from yarn, in Github Actions:
```bash
/usr/local/bin/yarn --frozen-lockfile
yarn install v1.22.19
[1/4] Resolving packages...
error Your lockfile needs to be updated, but yarn was run with `--frozen-lockfile`.
```

Looks like you need to update the yarn lockfile (forgot to commit it?)

**Comment by orefalo** [comment]
it worked, tests passed ;-)

**Comment by Tal500** [comment]
BTW: Looks like there is a nice Visual Studio Code plugin for Commitizen: [Visual Studio Code Commitizen Support](https://marketplace.visualstudio.com/items?itemName=KnisterPeter.vscode-commitizen)

**Comment by Tal500** [comment]
Need to mention the linking:
Related to #23

**Pull request merged**
