### PR TITLE
:bug: fix: REPL issue by using `esm-env-robust` instead

### PR DESCRIPTION
**Pull request by Tal500**
Fixing the discussion in https://github.com/orefalo/svelte-splitpanes/pull/39#issuecomment-1347089124

### CODE REVIEW

**Comment by Tal500** [comment]
> Hi Tal, why not just testing `typeof window !== 'undefined'` rather than importing a new dependency?

So there will be compile-time optimization for the end user, that allows code minification in no-so-old environment.

**Comment by orefalo** [comment]
Not understanding the issue?

Correct me if I am wrong, all modern code minification tools optimize dependencies as well...

**Comment by Tal500** [comment]
> Not understanding the issue.
> 
> Correct me if I am wrong, all modern code minification tools optimize dependencies as well...

They will optimize the dependencies right, so the extra overhead of the automatically installed tiny new package will have zero cost in the end user runtime, and a very tiny cost for the development/build time, since the package `esm-env-robust` is tiny in its size.

The idea is that on older environment, like REPL, the constant variable `BROWSER` will resolve to `typeof window...`, but on the major updated environments this will resolve to a constant in compile time - `true` or `false`(see the README there for a full explanation), allowing minification.

So yes, the amount of lines of codes in this project depending on the `BROWSER` constant are few, but the extra auto-installed package is tiny and should have zero-cost on the final build.

I thought this package can be a role model for the Svelte society as well :-)

**Comment by orefalo** [comment]
Please be patient with me, remember I am not as fast as you are, plus you know how much I like to keep things simple...

I have the feeling... you are trying to solve two different issues (related, I admit)

1. fixing splitpanes with REPL -> correct me if I am wrong, a simple `isWindow() { return typeof window !== 'undefined'}` in the code would do.
2. coming with a more optimized approach to solve the issue -> my recommendation would be to draft a project simpler than splitpanes to make your case.

am I missing anything?

**Comment by Tal500** [comment]
> Please be patient with me, remember I am not as fast as you are, plus you know how much I like to keep things simple...
> 
> I have the feeling... you are trying to solve two different issues (related, I admit)
> 
>     1. fixing splitpanes with REPL -> correct me if I am wrong, a simple `isWindow() { return typeof window !== 'undefined'}` in the code would do.
> 
>     2. coming with a more optimized approach to solve the issue -> my recommendation would be to draft a project simpler than splitpanes to make your case.
> 
> 
> am I missing anything?

You got that right and understood it well! Just want to add more context that may convince you.

The original way to determine if on browser, was to use `$app/environement`, but that requires the user of the library to be in the SvelteKit environment(e.g. not working with REPL, sapper or any other). The advantage of this way was that it's being resolved in compile time.

Therefore, I opened an issue in https://github.com/sveltejs/kit/issues/5879. Ben was insisting that the constant will be resolved in compile time. In the last comment there, Ben opened a new issue https://github.com/sveltejs/kit/issues/8033: Ben tried to solve this issue by introducing a new package - `esm-env`, that gives the correct constants by using modern NPM tricks.

The problem with his method is that it wasn't working with REPL, so I opened a new issue https://github.com/benmccann/esm-env/issues/1 reporting this. There could be two solution for this:
1. Fix the REPL to read the `exports` field in `package.json`
2. Make the `esm-env` more robust.

It seems that solution 1 will take time, and I wasn't sure that Ben will like to apply solution 2. So as a compromise, I had created the new package `esm-env-robust` that fixes 2.

It seems that Ben wants Svelte society to go in the `esm-env` direction, so I wanted to apply this logic here as well because I liked this compile-time resolution trick.

But if you think it's an overkill so you can revert this specific lines of code and remove the new tiny dependency, and assign the `BROWSER` value to be `typeof window !== 'undefined'` (i.e. runtime resolution).

Just thought that it can be cool in the sprit of upgrading all the Svelte packages dependencies.

**Comment by orefalo** [comment]
Thank you - I now fully understand the context.

Maybe, you should point on this ticket, https://github.com/sveltejs/kit/issues/8033  about the new 'robust' version of esm-end

let me do it.

**Comment by orefalo** [comment]
@Tal500 on a 1-1, I don't understand how you esm-*-robust code works. I read it.. I think it's beyond me ;-)

**Comment by Tal500** [comment]
> @Tal500 on a 1-1, I don't understand how you esm-*-robust code works. I read it.. I think it's beyond me ;-)

hhh it's more abuse of NPM standards than code...
It is much easier to understand the original [esm-env](https://github.com/benmccann/esm-env) implementation, which inspired my idea to make it more robust.

Look at the [`exports` field in the `package.json` file of esm-env](https://github.com/benmccann/esm-env/blob/bddcec345fe2c4f0779a590d389320f4ec60ba2b/package.json#L12-L24).
This tells npm how to map the '.' path to the actual implementation file.
The interesting thing is that it branches over the cases of the current environment - "browser" vs "default", and "development" vs "default". While the types are shared among all of them and noted by the line [`"types": "./index.d.ts"`](https://github.com/benmccann/esm-env/blob/bddcec345fe2c4f0779a590d389320f4ec60ba2b/package.json#L14), the source file varies according to the current environment, where each source file implements the constants according to the right behavior.

What I did in esm-env-robust is to:
1. Import `esm-env` when the environment supports the `exports` field of `package.json`.
2. In the case it doesn't, fool the system by giving a direct implementation of the JS files(the one outside the 'internal' directory) , acting as a "fallback".

**Comment by orefalo** [comment]
Now I got it, thank you. Just learned about these new package.json entries.

**Comment by Tal500** [comment]
Since Svelte team aren't willing to fix REPL yet(might be hard work), I believe we should just merge it, and if we won't like/not need it in the future, we can just revert.

This merge will be transparent to the user.

**Comment by orefalo** [comment]
IMHO, 
We are comparing correctness against simplicity.

1. The most simple way to solve this bug is to replace the code with a window check.
2. The correct way is to implement your npm bypass accepting that it add to the readability of the code, for really... one line of code.

I personally believe in simplicity. #1 with a simple comment would do just fine.

**Comment by Tal500** [comment]
> 

OK, so we should just remove the `esm-env` dep, and put back the `typeof window` check (in master branch)

**Comment by Tal500** [comment]
> IMHO, We are comparing correctness against simplicity.
> 
>     1. The most simple way to solve this bug is to replace the code with a window check.
> 
>     2. The correct way is to implement your npm bypass accepting that it add to the readability of the code, for really... one line of code.
> 
> 
> I personally believe in simplicity. #1 with a simple comment would do just fine.

As you suggested, fixed alternatively by 8069f7a09a8cc28b94c6b18d01769e4cc3207d75

**Pull request closed without merging**
