### PR TITLE
Auto docs generation.

### PR DESCRIPTION
**Pull request by Tal500**
This one is important, and @orefalo must merge it by himself.

This PR use GitHub Action for publishing the docs automatically, every time someone pushes to master.
For making this work, you need to merge this PR, and configure GitHub Pages setting (only the maintainer can do so), to be set to the branch `gh-pages` and to the path `docs/`, as you can see here:
תמונה

Notice that this PR also deletes the folder `docs` from master (as it should not be there!!), and generate the docs only for "gh-pages" branch, that should **NEVER** be merged (if accidentally merge, just revert or delete `docs`).

This is what is done internally, whenever someone pushes to the master branch:
1. Build the project (docs).
2. Push them to the branch `gh-pages`.
After this two, GitHub Pages automatic system takes the `docs/` in the branch `gh-pages` and publish it as you already know.

### CODE REVIEW

**Comment by orefalo** [comment]
you should have tell me... it's already configured.

not via an action, but via github itself -> you can tell github to pick gh-pages from a specific folder in the repo.

ah.. but I see... we still need to manually generate the docs folder and push it, which is what is PR does.

**Comment by Tal500** [comment]
> you should have tell me... it's already configured.
> 
> not via an action, but via github itself -> you can tell github to pick gh-pages from a specific folder in the repo. (it's actually the screenshot you provided)
> 
> ah.. but I see... we still need to manually generate the docs folder and push it, which is what this PR does.

Yes, but I want you to notice it's super important to select the newly generated "gh-pages" branch.

**Comment by Tal500** [comment]
Related to #23 BTW

**Comment by Tal500** [comment]
I see still the github pages marked as failed.
Did you change the setting I showed to take the `docs` **from the branch `gh-pages`**?

**Pull request merged**
